apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apicurio-registry.fullname" . }}
  labels:
    {{- include "apicurio-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apicurio-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apicurio-registry.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "apicurio-registry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "REGISTRY_DATASOURCE_URL"
            value: "{{ .Values.config.registryDataSource.url }}"
          - name: "REGISTRY_DATASOURCE_USERNAME"
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.config.registryDataSource.existingSecret }}"
                key: "{{ .Values.config.registryDataSource.existingSecretUserNameKey }}"
          - name: "REGISTRY_DATASOURCE_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.config.registryDataSource.existingSecret }}"
                key: "{{ .Values.config.registryDataSource.existingSecretPasswordKey }}"
          {{- if .Values.config.security.enabled }}
          - name: AUTH_ENABLED
            value: "{{ .Values.config.security.enabled }}"
           - name: KEYCLOAK_URL
            value: "{{ .Values.config.security.keycloakUrl }}"
          - name: KEYCLOAK_REALM
            value: "{{ .Values.config.security.keycloakRealm }}"
          - name: KEYCLOAK_API_CLIENT_ID
            value: "{{ .Values.config.security.keycloakApiClientId }}"
          - name: KEYCLOAK_UI_CLIENT_ID
            value: "{{ .Values.config.security.keycloakUiClientId }}"        
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
