apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cmak.fullname" . }}-config
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  application.conf: |-
    cmak {
      broker-view-thread-pool-size: 6
      broker-view-max-queue-size: 100
      broker-view-update-seconds: 30
      offset-cache-thread-pool-size: 10
      offset-cache-max-queue-size: 1000
      kafka-admin-client-thread-pool-size: 10
      kafka-admin-client-max-queue-size: 1000
    }
    application {
      features: ["KMClusterManagerFeature","KMTopicManagerFeature","KMPreferredReplicaElectionFeature","KMReassignPartitionsFeature"]
    }